# Generated by Django 4.2.9 on 2026-02-16 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_section_alter_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_id',
            field=models.CharField(blank=True, help_text='School-assigned teacher ID (e.g. TCH-2024-001)', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Links teachers/students to their school account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('student_id__gt', '')), fields=('school', 'student_id'), name='unique_student_id_per_school'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher_id__gt', '')), fields=('school', 'teacher_id'), name='unique_teacher_id_per_school'),
        ),
    ]
