# Generated by Django 4.2.9 on 2026-02-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='board',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('STATE', 'State Board'), ('ICSE', 'ICSE'), ('INTL', 'International')], default='CBSE', max_length=10),
        ),
    ]
