# Generated by Django 4.2.9 on 2026-02-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_international_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('coaching', 'Coaching Centre')], default='school', max_length=10),
        ),
    ]
