# Generated by Django 4.2.9 on 2026-02-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_extend_grade_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_from',
            field=models.PositiveIntegerField(default=1, help_text='Lowest class offered (e.g. 1)'),
        ),
        migrations.AddField(
            model_name='user',
            name='class_to',
            field=models.PositiveIntegerField(default=12, help_text='Highest class offered (e.g. 10)'),
        ),
    ]
