# Generated by Django 4.2.9 on 2026-02-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_class_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='board',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('STATE', 'State Board'), ('ICSE', 'ICSE'), ('INTL', 'International'), ('BANK', 'Bank Exams'), ('EAMCET', 'EAMCET'), ('ECET', 'ECET'), ('NEET', 'NEET'), ('JEE', 'IIT-JEE'), ('DSC', 'DSC'), ('OTHER', 'Other')], default='CBSE', max_length=10),
        ),
    ]
