# Generated by Django 4.2.9 on 2026-02-14 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_teacherassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwrittenExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('answer_sheet', models.FileField(upload_to='handwritten/answers/%Y/%m/')),
                ('question_paper', models.FileField(upload_to='handwritten/questions/%Y/%m/')),
                ('total_marks', models.IntegerField(default=50)),
                ('obtained_marks', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('GRADED', 'Graded'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('grading_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_exams', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_taken', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handwritten_exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSheetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_sheet_image', models.ImageField(upload_to='answer_sheets/%Y/%m/')),
                ('answer_key_file', models.FileField(blank=True, null=True, upload_to='answer_keys/%Y/%m/')),
                ('ai_valuation', models.JSONField(blank=True, default=dict, help_text='AI valuation results')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='AI analysis data')),
                ('teacher_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheet_uploads', to='exams.assignedexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_answer_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer_sheet_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
