# Generated by Django 4.2.9 on 2026-02-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_handwrittenexam_answersheetupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexam',
            name='grading_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_REVIEW', 'Pending Teacher Review'), ('GRADING_MCQ', 'Grading MCQs'), ('GRADING_DESCRIPTIVE', 'AI Grading Descriptive'), ('ANALYZING', 'Generating Analysis'), ('COMPLETED', 'Grading Complete'), ('FAILED', 'Grading Failed')], default='NOT_STARTED', max_length=25),
        ),
    ]
