# Generated by Django 4.2.9 on 2026-02-15 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0005_add_pending_review_grading_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='grade',
            field=models.CharField(default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='section',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'subject', 'grade', 'section')},
        ),
        migrations.RemoveField(
            model_name='teacherassignment',
            name='students',
        ),
    ]
