# Generated by Django 4.2.9 on 2026-02-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_teacherassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedexam',
            name='num_questions',
        ),
        migrations.AddField(
            model_name='assignedexam',
            name='num_long',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='assignedexam',
            name='num_mcq',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='assignedexam',
            name='num_short',
            field=models.IntegerField(default=5),
        ),
    ]
