# Generated by Django 4.2.9 on 2026-02-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_assignedexam_num_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedexam',
            name='selected_questions',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to='exams.question'),
        ),
        migrations.AddField(
            model_name='assignedexam',
            name='selection_mode',
            field=models.CharField(choices=[('random', 'Random from Question Bank'), ('manual', 'Manually Selected')], default='random', max_length=10),
        ),
    ]
