# Generated by Django 4.2.9 on 2026-02-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_assignedexam_selected_questions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['grade', 'name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Class/grade this subject belongs to (e.g. 10)', max_length=5),
        ),
    ]
