# Generated by Django 4.2.9 on 2026-02-21 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0009_add_grade_to_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School/org that owns this subject (null = global/shared)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('exam_type', 'code', 'school')},
        ),
    ]
