# Generated by Django 4.2.9 on 2026-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_subject_unique_together_subject_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='section',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
