# Generated by Django 4.2.9 on 2026-02-25 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0011_alter_teacherassignment_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Specific students assigned to this teacher for this subject', related_name='teacher_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
